name: Java CI with Maven 

on:
  push:
    branches: [ "master" ]
  pull_request: # só para pull
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
# Render Deploy Action 
    - name: Render Deploy Action0
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: srv-cr26v8rqf0us739nqdmg
        api-key: rnd_SLBw9GDEL1ePvt1a9ADf7p44kMp3
    - name: Deploy EC2
        run: |
          echo "${{secrets.KEY_EC2_JAVA}}" >private_key && chmod 400 "private_key" 
          ssh -o StrictHostKeyChecking=no -i "private_key" ubuntu@ec2-44-213-235-105.compute-1.amazonaws.com "
            cd /home/ubuntu/ApiProduto
            git pull
            mvn clean package -DskipTests
            ./executar.sh "
